[workspace]

members = [
    "./analyzer-dispatcher",
    "./derive-dynamic-node",
    "./endpoint-plugin",
    "./graph-descriptions",
    "./graph-merger",
    "./grapl-config",
    "./grapl-observe",
    "./metric-forwarder",
    "./node-identifier",
    "./generators/graph-generator-lib",
    "./generators/generic-subgraph-generator",
    "./generators/osquery-subgraph-generator",
    "./generators/sysmon-subgraph-generator",
    "./sqs-executor",
    "./grapl-service",
]
