[package]
name = "sysmon-subgraph-generator"
version = "1.0.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

[dependencies]
grapl-graph-descriptions = { path="../../graph-descriptions", version="*" }
grapl-config = {path = "../../grapl-config", version="*"}
grapl-observe = {path = "../../grapl-observe", version="*"}

<<<<<<< HEAD
#sqs-lambda = { path = "../../sqs-lambda/" }
sqs-executor = { path = "../../sqs-executor/" }
grapl-service = { path = "../../grapl-service/" }
serde = "1.0.110"
serde_json = "1.0.53"
serde_derive = "1.0.110"
failure = "0.1.*"
prost = "0.6.*"
log = "0.4.3"
base16 = "0.1.1"
regex = "1.1.0"
lazy_static = "1.2.0"
=======
sqs-lambda = { path = "../../sqs-lambda/" }
serde = "1"
serde_json = "1"
serde_derive = "1"
failure = "0.1"
prost = "0.7"
log = "0.4"
regex = "1"
lazy_static = "1.4"
>>>>>>> staging
sysmon = "0.2"
chrono = "0.4"
stopwatch = "0"

rusoto_s3 = {version="0.45.0", default_features = false, features=["rustls"]}
rusoto_core = {version="0.45.0", default_features = false, features=["rustls"]}
rusoto_sqs = {version="0.45.0", default_features = false, features=["rustls"]}
rusoto_credential = "0.45.0"
<<<<<<< HEAD
futures = "0.3.*"
aws_lambda_events = "0.2.0"

simple_logger = "1.6.*"
lambda_runtime = "0.2.*"
async-trait = "0.1.31"
zstd = "0.5.1"
tokio-compat = "0.1.*"
tokio = { version = "0.2.*", features = ["sync", "rt-core", "macros", "time", "rt-threaded"] }
graph-generator-lib = { path="../graph-generator-lib", version="*"}
tracing = "0.1.15"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
thiserror = "1.0.22"
=======
futures = "0.3"
aws_lambda_events = "0.4"
>>>>>>> staging

lambda_runtime = "0.2"
async-trait = "0.1"
zstd = "0.6"
tokio-compat = "0.1"
tokio = { version = "0.2", features = ["sync", "rt-core", "macros", "time", "rt-threaded"] }
graph-generator-lib = { path="../graph-generator-lib" }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[dependencies.uuid]
version = "*"
features = ["v4"]