# NOTE: This configuration file is ONLY for Black and
# isort. Additionally, its usage is deprecated in favor of the
# pyproject.toml file at the repository root. Any configuration
# changes should instead be made in *that* file.
#
# This file will be deleted soon.

# pyproject as specified by PEP 518

[tool.black]
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  (\w*_pb2\w*.py.*)
)
'''

[tool.isort]
# Black-recommended isort settings
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

# grapl analyzerlib's import ordering is very very touchy
skip_glob = ["grapl_analyzerlib/**"]
