[package]
name = "sqs-executor"
version = "0.1.0"
authors = ["colin <colin@graplsecurity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grapl-observe = {path = "../grapl-observe"}

rusoto_core = {version = "^0", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "^0", default_features = false, features=["rustls"]}
rusoto_sqs = {version = "^0", default_features = false, features=["rustls"]}

tokio = { version = "0.2", features = ["io-util", "sync", "rt-core", "macros", "time", "rt-threaded"] }

serde = "1.0"
serde_json = "1.0"
prost = "0.6.*"
zstd = "0.5.1"
eyre = "0.6.3"
color-eyre = "0.5.10"
thiserror = "1.0.22"
async-trait = "0.1.42"
tracing = "0.1.22"
tracing-futures = "0.2.4"
futures-util = "0.3.8"
uuid = {version = "0.8.1", features=["v4"]}
futures = "0.3.8"
