[package]
name = "node-identifier"
version = "1.0.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

[[bin]]
name = "node-identifier"
path = "src/bin/node-identifier.rs"


[[bin]]
name = "node-identifier-retry-handler"
path = "src/bin/node-identifier-retry-handler.rs"

[features]
integration = []

[dependencies]
grapl-graph-descriptions = { path="../graph-descriptions", version="*"}
grapl-config = {path="../grapl-config", version="*"}
grapl-observe = {path="../grapl-observe", version="*"}
grapl-service = {path="../grapl-service"}

bytes = "1"
failure = "0.1"
prost = "0.7"

base64 = "0.13"

rusoto_s3 = {version="0.45", default_features = false, features=["rustls"]}
rusoto_core = {version="0.45", default_features = false, features=["rustls"]}
rusoto_sqs = {version="0.45", default_features = false, features=["rustls"]}
rusoto_dynamodb = {version="0.45", default_features = false, features=["rustls"]}
rusoto_credential = "0.45"
serde_dynamodb = {version="0.6", default_features = false, features=["rustls"]}

lambda_runtime = "0.2"

sha2 = "0.9"
log = "0.4"
stopwatch = "0"

<<<<<<< HEAD
zstd = "0.5.1"
futures = "0.3.*"
sqs-executor = { path = "../sqs-executor/" }
=======
zstd = "0.6"
futures = "0.3"
sqs-lambda = { path = "../sqs-lambda/" }
>>>>>>> staging

aws_lambda_events = "0.4"

serde = "1"
serde_json = "1"
serde_derive = "1"

<<<<<<< HEAD
hex = "0.4.0"
async-trait = "0.1.21"
tokio-compat = "0.1.*"
tokio = { version = "0.2.*", features = ["sync", "rt-core", "macros", "time", "rt-threaded"] }
hmap = "0.1.0"
tracing = "0.1.13"
chrono = "0.4.11"
thiserror = "1.0.23"
=======
hex = "0.4"
async-trait = "0.1"
tokio-compat = "0.1"
tokio = { version = "0.2", features = ["sync", "macros", "time", "rt-threaded"] }
hmap = "0.1"
tracing = "0.1"
chrono = "0.4"
>>>>>>> staging

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"