[package]
name = "osquery-subgraph-generator"
version = "0.1.0"
authors = ["Nathanial Lattimer <nlattimer@graplsecurity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grapl-graph-descriptions = { path="../../graph-descriptions", version="*" }
grapl-config = { path = "../../grapl-config", version="*" }
grapl-observe = { path = "../../grapl-observe", version="*" }
graph-generator-lib = { path="../graph-generator-lib", version="*" }
grapl-service = { path = "../../grapl-service" }

<<<<<<< HEAD

sqs-executor = { path = "../../sqs-executor/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1.*"
log = "0.4.3"
regex = "1.3.9"
=======
sqs-lambda = { path = "../../sqs-lambda/" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
failure = "0.1"
log = "0.4"
regex = "1"
>>>>>>> staging

rusoto_s3 = {version="0.45.0", default_features = false, features=["rustls"]}
rusoto_core = {version="0.45.0", default_features = false, features=["rustls"]}
rusoto_sqs = {version="0.45.0", default_features = false, features=["rustls"]}

<<<<<<< HEAD
lambda_runtime = "0.2.*"
async-trait = "0.1.31"
zstd = "0.5.1"
tokio-compat = "0.1.*"
tokio = { version = "0.2.*", features = ["sync", "rt-core", "macros", "time", "rt-threaded", "fs"] }
thiserror = "1.0.23"
tracing = "0.1.22"
=======
lambda_runtime = "0.2"
async-trait = "0.1"
zstd = "0.6"
tokio-compat = "0.1"
tokio = { version = "0.2", features = ["sync", "rt-core", "macros", "time", "rt-threaded", "fs"] }
>>>>>>> staging
