[package]
name = "graph-generator-lib"
version = "0.1.9"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"
description = "Library for writing Grapl generator services"
license = "Apache-2.0"

[dependencies]
grapl-graph-descriptions = { path="../../graph-descriptions", version="0.2.*" }
grapl-observe = {path = "../../grapl-observe/"}
sqs-executor = {path="../../sqs-executor"}
grapl-service = {path="../../grapl-service"}
rusoto_s3 = { version="0.45.0", default_features = false, features=["rustls"] }
rusoto_core = { version="0.45.0", default_features = false, features=["rustls"] }
rusoto_sqs = { version="0.45.0", default_features = false, features=["rustls"] }
rusoto_sts =  { version="0.45.0", default_features = false, features=["rustls"] }
grapl-config = { path="../../grapl-config", version="0.0.*" }
tracing = "0.1.22"
